var TRACKS = [
  {slug:"sunday-slow-01", name:"sunday slow 01", cat:"groove", file:"radio/rooms/groove/sunday-slow-01.mp3"},
  {slug:"sunday-slow-02", name:"sunday slow 02", cat:"groove", file:"radio/rooms/groove/sunday-slow-02.mp3"},
  {slug:"the-serpent-ate-the-treasure", name:"the serpent ate the treasure", cat:"drift", file:"radio/rooms/drift/the-serpent-ate-the-treasure.mp3"},
  {slug:"road-trip-to-zamfara", name:"road trip to zamfara", cat:"groove", file:"radio/rooms/groove/road-trip-to-zamfara.mp3"},
  {slug:"riverbend-808", name:"riverbend 808", cat:"groove", file:"radio/rooms/groove/riverbend-808.mp3"},
  {slug:"yingi-yanga", name:"yingi yanga", cat:"groove", file:"radio/rooms/groove/yingi-yanga.mp3"},
  {slug:"coco-coconut", name:"coco coconut", cat:"groove", file:"radio/rooms/groove/coco-coconut.mp3"},
  {slug:"rasta-savasana", name:"rasta savasana", cat:"drift", file:"radio/rooms/drift/rasta-savasana.mp3"},
  {slug:"945-in-kingston", name:"945 in kingston", cat:"drift", file:"radio/rooms/drift/945-in-kingston.mp3"},
  {slug:"a-man-a-guitar-and-vuvuzela-went-to-a-bar", name:"a man, a guitar and vuvuzela went to a bar", cat:"groove", file:"radio/rooms/groove/a-man-a-guitar-and-vuvuzela-went-to-a-bar.mp3"},
  {slug:"yogapiano", name:"yogapiano", cat:"groove", file:"radio/rooms/groove/yogapiano.mp3"},
  {slug:"zouk-asana", name:"zouk-asana", cat:"groove", file:"radio/rooms/groove/zouk-asana.mp3"},
  {slug:"kizomba-my-heart", name:"kizomba my heart", cat:"groove", file:"radio/rooms/groove/kizomba-my-heart.mp3"},
  {slug:"they-said-buddha-cant-run", name:"they said buddha cant run", cat:"drift", file:"radio/rooms/drift/they-said-buddha-cant-run.mp3"},
  {slug:"cello-phane-clouds", name:"cello-phane clouds", cat:"drift", file:"radio/rooms/drift/cello-phane-clouds.mp3"},
  {slug:"cello-phane-again", name:"cello-phane again", cat:"drift", file:"radio/rooms/drift/cello-phane-again.mp3"},
  {slug:"sunset-no-delay", name:"sunset no delay", cat:"drift", file:"radio/rooms/drift/sunset-no-delay.mp3"},
  {slug:"lagos-quiet-hour", name:"lagos quiet hour", cat:"drift", file:"radio/rooms/drift/lagos-quiet-hour.mp3"},
  {slug:"rastas-nightmare", name:"rastas nightmare", cat:"drift", file:"radio/rooms/drift/rastas-nightmare.mp3"},
  {slug:"yanya-yingi", name:"yanya yingi", cat:"groove", file:"radio/rooms/groove/yanya-yingi.mp3"},
  {slug:"we-were-here-yesterday-01", name:"we were here yesterday 01", cat:"groove", file:"radio/rooms/groove/we-were-here-yesterday-01.mp3"},
  {slug:"we-were-here-yesterday-02", name:"we were here yesterday 02", cat:"drift", file:"radio/rooms/drift/we-were-here-yesterday-02.mp3"},
  {slug:"ancestor-hum", name:"ancestor hum", cat:"dust", file:"radio/rooms/dust/ancestor-hum.mp3"},
  {slug:"calm-shore", name:"calm shore", cat:"dust", file:"radio/rooms/dust/calm-shore.mp3"},
  {slug:"cartagena-breeze", name:"cartagena breeze", cat:"dust", file:"radio/rooms/dust/cartagena-breeze.mp3"},
  {slug:"kingston-raindrops", name:"kingston raindrops", cat:"dust", file:"radio/rooms/dust/kingston-raindrops.mp3"},
  {slug:"lagos-downpour", name:"lagos downpour", cat:"dust", file:"radio/rooms/dust/lagos-downpour.mp3"},
  {slug:"steady-rainfall", name:"steady rainfall", cat:"dust", file:"radio/rooms/dust/steady-rainfall.mp3"},
  {slug:"wakanda-waves", name:"wakanda waves", cat:"dust", file:"radio/rooms/dust/wakanda-waves.mp3"},
  {slug:"zanzibar-shallows", name:"zanzibar shallows", cat:"dust", file:"radio/rooms/dust/zanzibar-shallows.mp3"},
  {slug:"begin-again", name:"begin again", cat:"whisper", file:"radio/rooms/whisper/begin-again.mp3"}
];
